Add caution and for loop with to test some sample
add set -euo pipefail which will cause the script to exit
if pipe fails error occurs.[man bash for more if you need]

add a for loop which takes on all of the things in the directory
and if there is no files, returns with exit code 1 or if there are
files lists them

diff --git a/organizer b/organizer
--- a/organizer
+++ b/organizer
@@ -1,1 +1,13 @@
 #!/usr/bin/env bash
+
+set -euo pipefail
+trap 'echo "Error on line $LINENO"' ERR
+
+for all in *; do
+  if [[ ! -f $all ]]; then
+    echo "No files are there"
+    exit 1
+  else
+    echo "$all"
+  fi
+done
